### ISSUE TITLE
about the data

### ISSUE THREAD

**Issue by huhengtong** [RemySun/MVAGMLProject#1]
Why do you not provide the orginal Pascal Voc 2017 dataset, so that the programme can run directly?

**Comment by RemySun** [comment]
I did not include the dataset in the repository because it would weigh it down unnecessarily the repository for cloning. I also own none of the data so there is that.

You are right that I should have included a link to the data though: the dataset can be found at http://host.robots.ox.ac.uk/pascal/VOC/voc2007/ with annotations found at the bottom of page http://vision.cs.utexas.edu/projects/tag/cvpr10.html.

Unfortunately you would have to do a bit of fiddling to get this working, in particular with  data paths. It has been on my to do list to streamline this but I have not found the time to clean this up.
